spring.application.name=Workation_BE

server.servlet.context-path=/workation
server.port=8007

# MySQL 연동설정
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://localhost:3306/workation
spring.datasource.username=root
spring.datasource.password=mysql

# JPA 연동 설정
spring.jpa.hibernate.ddl-auto=update
# Entity 를 기준으로 테이블을 자동 생성/수정 

spring.jpa.show-sql=true
#내부적으로 JPA 가 만들어서 실행하는 SQL 문을 콘솔에 찍어주겠다.

spring.jpa.properties.hibernate.format_sql=true
#SQL 문을 출력할 때 보기 좋게 정렬해서 출력하겠다.

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
# 사용할 데이터베이스(MySQL) 에 맞는 SQL 문으로 생성하겠다.

jwt.secret=${JWT_SECRET:Hello123KHAcademy456Gangnam789WelcomeToHClass0}

app.init.super-admin.login-id=${SUPER_ADMIN_LOGIN_ID:admin}
app.init.super-admin.password=${SUPER_ADMIN_PASSWORD:test}

# 이메일 전송 관련 설정
# SMTP 서버 설정 (gmail 서버 설정)
spring.mail.host=${MAIL_HOST:smtp.gmail.com}
spring.mail.port=${MAIL_PORT:587}
spring.mail.username=${MAIL_USERNAME:siteblod@gmail.com}
spring.mail.password=${MAIL_PASSWORD:clox ugcc zmwx vvvd}

# 프로토콜 및 인코딩 설정
spring.mail.protocol=smtp
spring.mail.default-encoding=UTF-8

# 보안 관련 설정
spring.mail.properties.mail.smtp.auth=${MAIL_SMTP_AUTH:true}
spring.mail.properties.mail.smtp.starttls.enable=${MAIL_SMTP_STARTTLS_ENABLE:true}
spring.mail.properties.mail.smtp.starttls.required=${MAIL_SMTP_STARTTLS_REQUIRED:true}

# Swagger 설정
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html

# 파일 업로드 및 이미지
file.upload-dir=C:/Final_Project/Workation_BE/uploads/
spring.web.resources.static-locations=file:///C:/Final_Project/Workaction_BE/uploads/,classpath:/static/

# Multipart 파일 업로드 용량 제한 설정
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB

# Google Gemini API 연동 설정
# API 키 설정

# 사용할 Gemini 버전 선택
spring.ai.google.genai.chat.model=gemini-3.5-flash-lite

# Google GenAI 자동 설정 비활성화
spring.autoconfigure.exclude=org.springframework.ai.model.google.genai.autoconfigure.chat.GoogleGenAiChatAutoConfiguration